### ISSUE TITLE
Adding variables feature and documentation

### ISSUE THREAD

**Issue by himanshujaidka** [Kalaam-Programming-Language/Kalaam#19]
Hi @swanandapps I am here to support your Kalam-lang. Now, let's work together and make this language more suitable.
We could add documentation and features on different types of variables

**Comment by swanandapps** [comment]
@himanshujaidka We are working on the documentation, created a separate repo just for that. Once that's set up, you can start contributing to Documentation. Have you prepared anything for documentation yet?

**Comment by himanshujaidka** [comment]
No, but wants to prepare .!
